# qwen-1.7b-nsp.py

import os
import datetime
import random
from typing import Callable, Dict, List, Tuple, Any
import logging
import warnings
import math

import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer, PreTrainedModel
from vllm import LLM, SamplingParams
from vllm.model_executor import set_random_seed as vllm_set_random_seed
from unittest.mock import patch
from datasets import load_dataset
from torch.utils.tensorboard import SummaryWriter
import re
from dotenv import load_dotenv
load_dotenv()

logging.getLogger("vllm.engine.scheduler").setLevel(logging.ERROR)
os.environ["VLLM_USE_V1"] = "0"

from torch.optim.lr_scheduler import LambdaLR

def get_constant_schedule_with_warmup(optimizer: torch.optim.Optimizer, num_warmup_steps: int, last_epoch: int = -1):
    def lr_lambda(current_step: int):
        return min(1.0, float(current_step) / float(max(1, num_warmup_steps)))
    return LambdaLR(optimizer, lr_lambda, last_epoch)

# -------------------------
# Prompting helpers (Countdown-style)
# -------------------------
TEMPLATE = """Using the numbers {numbers}, create an equation that equals {target}. 
You can use basic arithmetic operations (+, -, *, /) and each number can only be used once.
Show your reasoning in <think> </think> tags. And return the final equation in <answer> </answer> tags. Keep your reasoning under {max_tokens} tokens.
For example, numbers = [1, 2, 3, 4] and target = 5, the answer is <answer>(1 + 2) * 3 - 4</answer>."""


# vLLM utilities
def init_vllm(model_id: str, device: str, seed: int, gpu_memory_utilization: float = 0.85) -> LLM:
    vllm_set_random_seed(seed)
    world_size_patch = patch("torch.distributed.get_world_size", return_value=1)
    profiling_patch = patch(
        "vllm.worker.worker.Worker._assert_memory_footprint_increased_during_profiling",
        return_value=None,
    )
    with world_size_patch, profiling_patch:
        return LLM(
            model=model_id,
            dtype=torch.bfloat16,
            enable_prefix_caching=True,
            gpu_memory_utilization=gpu_memory_utilization,
            max_model_len=2048
        )


def load_policy_into_vllm_instance(policy: PreTrainedModel, llm: LLM) -> None:
    state_dict = policy.state_dict()
    llm_model = llm.llm_engine.model_executor.driver_worker.model_runner.model
    llm_model.load_weights(state_dict.items())


def init_sampling_params(temperature: float, min_tokens: int, max_tokens: int) -> SamplingParams:
    sp = SamplingParams(
        temperature=temperature,
        top_p=1.0,
        min_tokens=min_tokens,
        max_tokens=max_tokens,
        logprobs=0,
    )
    sp.stop = ["</answer>"]
    sp.include_stop_str_in_output = True
    return sp


# Tokenization utilities
def tokenize_prompt_and_output(prompt_strs: List[str], output_strs: List[str], tokenizer: AutoTokenizer) -> Dict[str, torch.Tensor]:
    batch_data = []
    max_len = 0
    for prompt, output in zip(prompt_strs, output_strs):
        prompt_tokens = tokenizer(prompt)["input_ids"]
        output_tokens = tokenizer(output)["input_ids"]
        combined_tokens = prompt_tokens + output_tokens
        max_len = max(max_len, len(combined_tokens))
        batch_data.append({
            "tokens": combined_tokens, "prompt_len": len(prompt_tokens), "total_len": len(combined_tokens)
        })
    batch_size = len(batch_data)
    input_ids = torch.full((batch_size, max_len - 1), tokenizer.eos_token_id, dtype=torch.long)
    labels = torch.full((batch_size, max_len - 1), tokenizer.eos_token_id, dtype=torch.long)
    response_mask = torch.zeros((batch_size, max_len - 1), dtype=torch.bool)
    for i, data in enumerate(batch_data):
        tokens, seq_len = torch.tensor(data["tokens"]), len(data["tokens"])
        input_ids[i, :seq_len-1], labels[i, :seq_len-1] = tokens[:-1], tokens[1:]
        response_start, response_end = data["prompt_len"] - 1, seq_len - 1
        if response_end > response_start:
            response_mask[i, response_start:response_end] = True
    return {"input_ids": input_ids, "labels": labels, "response_mask": response_mask}



# Reward function and evaluation (Countdown solution)

# ==============================================================================
# TASK 1: Implement Reward Helper Functions
# Before you can write the reward function, you need to create three helper 
# functions to parse and evaluate the model's generated text.
# ==============================================================================

def _extract_answer(solution_str: str) -> str | None:
    """
    Extract the content from the last <answer>...</answer> tag in the given string.

    Hint: Use the `re` module. `re.finditer` can find all occurrences of a pattern.
    Args:
        solution_str: The full text generated by the model.

    Returns:
        The stripped string content of the last answer tag, or None if no tag is found.
    """
    ### YOUR CODE HERE ###
    if not solution_str:
        return None
    matches = list(re.finditer(r"<answer>\s*(.*?)\s*</answer>", solution_str, flags=re.DOTALL | re.IGNORECASE))
    return matches[-1].group(1).strip() if matches else None
    ### END YOUR CODE ###
    
# Input/Output Format:
rollout_response = "Okay, let's see. I need to use 79, 17, ... So the equation is ,→ <answer>(79 - (60 - 17))</answer>"
extracted_answer = _extract_answer(rollout_response)
assert extracted_answer == "(79 - (60 - 17))"
print("✅ extract_answer: Test passed!")


def _validate_numbers(equation_str: str, available_numbers: List[int]) -> bool:
    """
    Check if the numbers used in the equation are exactly the ones available.

    Hint:
    1. Use `re.findall(r"\d+", equation_str)` to get all number strings from the equation.
    2. Remember to handle potential errors and return False.

    Args:
        equation_str: The equation string to validate.
        available_numbers: A list of integers that are allowed to be used.

    Returns:
        True if the equation uses the correct numbers, False otherwise.
    """
    ### YOUR CODE HERE ###
    try: 
        # Extract all numbers from the equation 
        found_numbers = re.findall(r"\d+", equation_str)
        
        # Convert them into string
        str_found_numbers = list(map(int, found_numbers))
        
        # Compare (check for number & frequency - since each number must only appear once)
        return sorted(str_found_numbers) == sorted(available_numbers)
        
    except Exception:
        return False 
    ### END YOUR CODE ###
assert _validate_numbers("(79 - (60 - 17))", [79, 60, 17]) == True
assert _validate_numbers("(79 - 60)", [79, 60, 17]) == False
assert _validate_numbers("(79 - 17 - 17)", [79, 60, 17]) == False
assert _validate_numbers("79 + 60 + 17", [79, 17, 60]) == True
assert _validate_numbers("", [1, 2, 3]) == False

print("✅ validate_numbers: Tests passed!")


def _evaluate_equation(equation_str: str) -> float | None:
    """
    Safely evaluate a mathematical equation string.
    Args:
        equation_str: The equation string to evaluate.
    Returns:
        The result of the equation as a float, or None if it's invalid or unsafe.
    """
    ### YOUR CODE HERE ###
    try: 
        # Allows only valid characters
        if not re.fullmatch(r"[0-9+\-*/()\s]+", equation_str): 
            return None
        
        # Evaluate
        result = eval(equation_str, {"__builtins__": None}, {})

        # Return to float
        return float(result)
        
    except Exception:
        return None
    ### END YOUR CODE ###

# ==============================================================================
# TASK 2: Implement the Reward Function
# ==============================================================================
def reward_fn(generated_text: str, ground_truth: Dict, scale_factor: float = 5.0) -> float:
    """
    Reward function for countdown math problems.

    Your goal is to score the `generated_text` using the helper functions you just wrote.
    The function should return a dictionary with a "reward" key.

    Scoring criteria:
    - 1.0 (Perfect): The equation is valid, uses the correct numbers, and evaluates to the target.
    - 0.1 (Partial): The text contains an <answer> tag, but the equation is incorrect for any reason.
    - 0.0 (Failed): The `generated_text` does not contain an <answer> tag.

    Args:
        generated_text: The full text output from the language model.
        ground_truth: A dictionary containing `target` and `numbers`.

    Returns:
        A float value representing the reward, such as 1.0, 0.1, or 0.0
    """
    target = ground_truth.get("target")
    available_numbers = ground_truth.get("numbers", [])
    
    equation = _extract_answer(generated_text)
    if equation is None:
        return 0.0
    
    reward = 0.1
    
    if not _validate_numbers(equation, available_numbers):
        return reward
    
    reward += 0.1
    
    result = _evaluate_equation(equation)
    if result is None:
        return reward
    
    distance = abs(result - target)
    
    if distance < 1e-6:
        return 1.0
    
    # Hybrid approach: linear for small errors, exponential for large
    if distance <= scale_factor:
        # Linear decay for small errors
        distance_reward = 0.8 * (1.0 - distance / (2 * scale_factor))
    else:
        # Exponential decay for large errors
        distance_reward = 0.8 * math.exp(-(distance - scale_factor) / scale_factor) * 0.5
    
    return reward + max(0.0, distance_reward)

    # ### YOUR CODE HERE ###
    # target = ground_truth.get("target")
    # available_numbers = ground_truth.get("numbers", [])

    # # Extract Equation from <answer>
    # equation = _extract_answer(generated_text)
    # if equation is None:
    #     # No <answer> tag found
    #     return 0.0

    # # Validate Numbers
    # if not _validate_numbers(equation, available_numbers):
    #     # Has <answer> tag, but wrong numbers
    #     return 0.1

    # # Safely Evaluate
    # result = _evaluate_equation(equation)
    # if result is None:
    #     # Equation invalid for any reason
    #     return 0.1

    # # Check for Correctness
    # if abs(result - target) < 1e-6:
    #     return 1.0
    # else:
    #     return 0.1
    # ### END YOUR CODE ###


# -------------------------
# NSR (Negative Sample Reinforcement) utilities
# -------------------------
def get_reward_fn_for_mode(training_mode: str, use_binary_rewards: bool = False) -> Callable:
    """
    Return appropriate reward function based on training mode.
    
    For GRPO: Uses the sophisticated reward_fn with distance-based partial credit (0.0 to 1.0).
    For NSR modes: Uses binary rewards - strictly 1.0 for correct, -1.0 for incorrect.
    
    The binary nature is crucial for NSR's clean positive/negative sample decomposition.
    All partial rewards (0.1, 0.2, etc.) become -1.0 in NSR mode.
    
    Args:
        training_mode: "grpo", "nsr", or "weighted_reinforce"
        use_binary_rewards: If True, force binary rewards regardless of mode
    
    Returns:
        A reward function that takes (generated_text, ground_truth) and returns a float
    """
    if use_binary_rewards or training_mode in ["nsr", "weighted_reinforce"]:
        def binary_reward_wrapper(generated_text: str, ground_truth: Dict) -> float:
            # Use existing reward_fn to check correctness
            reward = reward_fn(generated_text, ground_truth)
            # For NSR: binary classification - only exactly correct (1.0) vs incorrect (-1.0)
            if abs(reward - 1.0) < 1e-6:
                return 1.0  # Correct
            else:
                return -1.0  # Incorrect (all partial rewards become -1)
        return binary_reward_wrapper
    else:
        # For GRPO: use existing sophisticated reward with partial credit
        return reward_fn


def compute_entropy(logits: torch.Tensor) -> float:
    """
    Compute average entropy of the output distribution.
    
    Args:
        logits: Logits tensor of shape [batch_size, seq_len, vocab_size]
    
    Returns:
        Average entropy across all positions
    """
    probs = F.softmax(logits, dim=-1)
    log_probs = F.log_softmax(logits, dim=-1)
    entropy = -(probs * log_probs).sum(dim=-1)
    return entropy.mean().item()


def compute_nsr_advantages(
    rollout_responses: List[str],
    repeated_ground_truths: List[Dict],
    reward_fn: Callable,
    group_size: int,
    training_mode: str,
    nsr_lambda: float = 0.1,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, Dict]:
    """
    Compute advantages for NSR and Weighted-REINFORCE training modes.
    
    For NSR: Only return advantages for incorrect responses (reward = -1).
             Correct responses get advantage = 0 and are filtered out during training.
    
    For Weighted-REINFORCE: Weight positive samples by lambda, full weight for negative.
                            Loss = -lambda * log_prob (for correct) - log_prob (for incorrect)
    
    Args:
        rollout_responses: List of generated responses (length = batch_size * group_size)
        repeated_ground_truths: Ground truth repeated for each response
        reward_fn: Function to compute rewards (should be binary_reward_fn for NSR)
        group_size: Number of responses per question (G)
        training_mode: "nsr" or "weighted_reinforce"
        nsr_lambda: Weight for correct samples in weighted_reinforce mode (default 0.1)
    
    Returns:
        advantages: Flattened tensor of advantages (shape: [batch_size * group_size])
        raw_rewards: Original rewards before processing
        response_filter_mask: Boolean mask indicating which responses to train on (True = train)
        metadata: Dictionary with 'mean', 'std', 'max', 'min' of raw rewards,
                  plus 'num_correct' and 'num_incorrect'
    """
    # 1. Calculate raw rewards (should be binary: 1.0 or -1.0)
    rewards = [reward_fn(resp, gt) for resp, gt in zip(rollout_responses, repeated_ground_truths)]
    raw_rewards = torch.tensor(rewards, dtype=torch.float32)
    
    # Count correct and incorrect responses
    num_correct = (raw_rewards > 0).sum().item()
    num_incorrect = (raw_rewards < 0).sum().item()
    
    # 2. Compute advantages based on training mode
    if training_mode == "nsr":
        # NSR: Only train on incorrect responses
        # Advantages are 1.0 for incorrect (to maximize -log_prob * advantage)
        # and 0.0 for correct (no gradient)
        advantages = torch.where(raw_rewards < 0, torch.ones_like(raw_rewards), torch.zeros_like(raw_rewards))
        response_filter_mask = raw_rewards < 0  # Only train on incorrect
        
    elif training_mode == "weighted_reinforce":
        # Weighted-REINFORCE: lambda weight for correct, full weight for incorrect
        # For correct (reward=1): advantage = lambda (reduce training on correct)
        # For incorrect (reward=-1): advantage = 1.0 (full training on incorrect)
        advantages = torch.where(raw_rewards > 0, 
                                torch.ones_like(raw_rewards) * nsr_lambda,
                                torch.ones_like(raw_rewards))
        response_filter_mask = torch.ones_like(raw_rewards, dtype=torch.bool)  # Train on all
        
    else:
        raise ValueError(f"Unknown training mode for NSR: {training_mode}")
    
    # 3. Metadata dictionary
    metadata = {
        "mean": torch.mean(raw_rewards),
        "std": torch.std(raw_rewards, unbiased=False),
        "max": torch.max(raw_rewards),
        "min": torch.min(raw_rewards),
        "num_correct": num_correct,
        "num_incorrect": num_incorrect,
    }
    
    return advantages, raw_rewards, response_filter_mask, metadata


def evaluate_model(llm: LLM, sampling_params: SamplingParams, eval_prompts: List[str], eval_answers: List[Dict]) -> Dict[str, Any]:
    """Evaluate the model on the given prompts."""
    rollouts = llm.generate(eval_prompts, sampling_params)
    examples, rewards, output_token_lengths = [], [], []
    
    for rollout, gt in zip(rollouts, eval_answers):
        response_text = rollout.outputs[0].text
        reward_value = reward_fn(response_text, gt)
        equation = _extract_answer(response_text)
        result = _evaluate_equation(equation) if equation is not None else None
        output_tokens = len(llm.llm_engine.tokenizer.encode(response_text))
        output_token_lengths.append(output_tokens)
        examples.append({
            "prompt": rollout.prompt, "response": response_text, "answer": gt, "equation": equation,
            "result": result, "reward": reward_value, "output_tokens": output_tokens,
        })
        rewards.append(reward_value)
    
    rewards_tensor = torch.tensor(rewards) if rewards else torch.tensor([0.0])
    tol = 1e-8
    count_correct = sum(1 for r in rewards if abs(r - 1.0) < tol)
    count_partial = sum(1 for r in rewards if abs(r - 0.1) < tol)
    count_failed = sum(1 for r in rewards if abs(r - 0.0) < tol)
    accuracy = (count_correct / len(rewards)) * 100 if rewards else 0.0
    avg_output_tokens = sum(output_token_lengths) / len(output_token_lengths) if output_token_lengths else 0.0
    
    return {
        "mean_reward": float(rewards_tensor.mean().item()),
        "std_reward": float(rewards_tensor.std().item()) if rewards_tensor.numel() > 1 else 0.0,
        "num_examples": len(rewards), "examples": examples, "count_correct": count_correct,
        "count_partial": count_partial, "count_failed": count_failed, "accuracy": accuracy,
        "avg_output_tokens": avg_output_tokens,
    }


def _format_eval_example(example: Dict[str, Any]) -> str:
    target = example["answer"]["target"] if isinstance(example.get("answer"), dict) and "target" in example["answer"] else "?"
    numbers = example["answer"].get("numbers") if isinstance(example.get("answer"), dict) else None
    return (
        f"Prompt: {example.get('prompt', '')}\n"
        f"Response: {example.get('response', '')}\n"
        f"Equation: {example.get('equation', None)} | Result: {example.get('result', None)} | Target: {target} | Numbers: {numbers}\n"
        f"Reward: {example.get('reward', 0.0):.3f}\n"
    )


def log_train(rollout_batch_loss: float, grad_norm: float, reward_metadata: Dict[str, Any], avg_output_tokens: float, writer: SummaryWriter | None, step: int) -> None:
    writer.add_scalar("train/loss", float(rollout_batch_loss), global_step=step)
    writer.add_scalar("train/grad_norm", float(grad_norm), global_step=step)
    writer.add_scalar("train/reward_mean", float(reward_metadata["mean"]), global_step=step)
    writer.add_scalar("train/reward_std", float(reward_metadata["std"]), global_step=step)
    writer.add_scalar("train/avg_output_tokens", float(avg_output_tokens), global_step=step)
    print(f"Step {step} | Loss: {rollout_batch_loss:.4f} | Grad norm: {grad_norm:.4f} | Reward mean: {float(reward_metadata['mean']):.4f} | Reward std: {float(reward_metadata['std']):.4f} | Avg output tokens: {avg_output_tokens:.1f}")


def log_eval(metrics: Dict[str, Any], writer: SummaryWriter | None, step: int) -> None:
    examples = metrics.get("examples", []) or []
    if not examples: return
    tol = 1e-8
    correct_examples = [ex for ex in examples if abs(float(ex.get("reward", 0.0)) - 1.0) < tol][:10]
    partial_examples = [ex for ex in examples if abs(float(ex.get("reward", 0.0)) - 0.1) < tol][:10]
    failed_examples = [ex for ex in examples if abs(float(ex.get("reward", 0.0)) - 0.0) < tol][:10]
    if correct_examples:
        print(f"\n=== Eval examples (CORRECT, reward=1.0) @ step {step} ===")
        for idx, ex in enumerate(correct_examples[:2], 1): print(f"[CORRECT #{idx}]\n" + _format_eval_example(ex))
    if partial_examples:
        print(f"\n=== Eval examples (PARTIAL, reward=0.1) @ step {step} ===")
        for idx, ex in enumerate(partial_examples[:2], 1): print(f"[PARTIAL #{idx}]\n" + _format_eval_example(ex))
    if failed_examples:
        print(f"\n=== Eval examples (FAILED, reward=0.0) @ step {step} ===")
        for idx, ex in enumerate(failed_examples[:2], 1): print(f"[FAILED #{idx}]\n" + _format_eval_example(ex))
    if writer:
        correct_text = "\n\n".join([_format_eval_example(ex) for ex in correct_examples]) or ""
        partial_text = "\n\n".join([_format_eval_example(ex) for ex in partial_examples]) or ""
        failed_text = "\n\n".join([_format_eval_example(ex) for ex in failed_examples]) or ""
        if correct_text: writer.add_text("eval/examples_correct", correct_text, global_step=step)
        if partial_text: writer.add_text("eval/examples_partial", partial_text, global_step=step)
        if failed_text: writer.add_text("eval/examples_failed", failed_text, global_step=step)
    print(f"Eval @ step {step}: accuracy={metrics['accuracy']:.1f}% mean_reward={metrics['mean_reward']:.4f} "
          f"avg_tokens={metrics['avg_output_tokens']:.1f} | correct:{metrics['count_correct']} "
          f"partial:{metrics['count_partial']} failed:{metrics['count_failed']}")


# -------------------------
# Advantages and GRPO-clip loss
# -------------------------
# ==============================================================================
# TASK 3: Implement Group Normalized Advantages
# ==============================================================================
def compute_group_normalized_advantages(
    rollout_responses: List[str],
    repeated_ground_truths: List[Dict],
    reward_fn: Callable[[str, Dict], float],
    group_size: int,
    advantage_eps: float,
    normalize_by_std: bool,
) -> Tuple[torch.Tensor, torch.Tensor, Dict[str, torch.Tensor]]:
    """ Computes advantages by normalizing rewards within groups.
    
    Args:
        rollout_responses: List of generated responses (length = batch_size * group_size)
        repeated_ground_truths: Ground truth repeated for each response
        reward_fn: Function to compute rewards
        group_size: Number of responses per question (G)
        advantage_eps: Small constant for numerical stability (epsilon)
        normalize_by_std: If True, normalize by std (GRPO); if False, don't (DR-GRPO)
    
    Returns:
        advantages: Flattened tensor of advantages (shape: [batch_size * group_size])
        raw_rewards: Original rewards before normalization
        metadata: Dictionary with 'mean', 'std', 'max', 'min' of raw rewards
            (e.g. metadata = {
                "mean": torch.mean(raw_rewards),
                "std": torch.std(raw_rewards),
                "max": torch.max(raw_rewards),
                "min": torch.min(raw_rewards),
            })
    """

    # Steps:
    # 1. Calculate the raw reward for each response using the provided `reward_fn`.
    # 2. Reshape the 1D tensor of raw rewards into a 2D tensor of shape (-1, `group_size`).
    # 3. Calculate the mean reward for each group.
    # 4. Compute the advantage by subtracting the group's mean reward.
    # 5. If `normalize_by_std` is True, normalize advantages by `(group_std + advantage_eps)`.
    # 6. Flatten the advantages tensor back into a 1D tensor.
    # 7. Create a `metadata` dictionary with overall statistics of the raw rewards.
    advantages, raw_rewards, metadata = None, None, {}
    ### YOUR CODE HERE ###
    # 1. Calculate raw rewards
    rewards = [reward_fn(resp, gt) for resp, gt in zip(rollout_responses, repeated_ground_truths)]
    raw_rewards = torch.tensor(rewards, dtype=torch.float32)

    # 2. Reshape into groups
    batch_size = len(raw_rewards) // group_size
    rewards_grouped = raw_rewards.view(-1, group_size) # (-1, group_size)

    # 3. Compute group mean and std
    group_mean = rewards_grouped.mean(dim=1, keepdim=True)
    group_std = rewards_grouped.std(dim=1, keepdim=True, unbiased=False)

    # 4. Compute advantage (subtract group mean)
    advantages = rewards_grouped - group_mean

    # 5. Optionally normalize by std
    if normalize_by_std:
        advantages = advantages / (group_std + advantage_eps)

    # 6. Flatten back to 1D
    advantages = advantages.flatten()

    # 7. Metadata dictionary
    metadata = {
        "mean": torch.mean(raw_rewards),
        "std": torch.std(raw_rewards, unbiased=False),
        "max": torch.max(raw_rewards),
        "min": torch.min(raw_rewards),
    }
    
    ### END YOUR CODE ###
    return advantages, raw_rewards, metadata


# ==============================================================================
# TASK 4: Implement per-token Loss
# ==============================================================================
def compute_loss(
    advantages: torch.Tensor,
    policy_log_probs: torch.Tensor,
    old_log_probs: torch.Tensor,
    clip_range: float,
    training_mode: str = "grpo",
) -> Tuple[torch.Tensor, Dict[str, torch.Tensor]]:
    """
    Computes the per-token PPO clipped surrogate loss.

    Why omit the KL divergence term?
    For simplicity and following trends in recent RLVR (e.g Dr.GRPO),
    we omit the KL penalty term often found in PPO. This simplifies the implementation
    and has been shown to work well in practice.

    NSR Mode:
    For NSR (Negative Sample Reinforcement), we use a simplified loss:
    - For incorrect samples (with advantage > 0): loss = log_prob (to decrease probability)
    - For correct samples: advantage = 0, so no gradient
    - No clipping or ratio computation needed for NSR (simpler than PPO)

    Steps:
    1. Calculate the probability ratio `pi_ratio = exp(policy_log_probs - old_log_probs)`.
    2. Calculate the unclipped term: `advantages * pi_ratio`.
    3. Calculate the clipped term by clipping `pi_ratio` to `[1-clip_range, 1+clip_range]`
       and then multiplying by `advantages`.
    4. The final loss is `-torch.minimum(unclipped_term, clipped_term)`.
    """
    loss = 0.0
    ### YOUR CODE HERE ###

    if training_mode in ["nsr", "weighted_reinforce"]:
        # NSR/Weighted-REINFORCE: Simplified REINFORCE loss without clipping
        # For incorrect (advantage=1): loss = +log_prob (decreases probability)
        # For correct in weighted_reinforce (advantage=lambda): loss = +lambda*log_prob
        # We use +log_prob because we want to decrease prob of incorrect responses
        loss = policy_log_probs * advantages
        
        # Stats for logging
        stats = {
            "ratio_mean": torch.tensor(1.0),  # No ratio in NSR
            "ratio_std": torch.tensor(0.0),
            "ratio_min": torch.tensor(1.0),
            "ratio_max": torch.tensor(1.0),
        }
    else:
        # Standard GRPO/PPO with clipping
        # 1. Ratio between new and old policies
        pi_ratio = torch.exp(policy_log_probs - old_log_probs)

        # 2. Unclipped term
        unclipped = advantages * pi_ratio

        # 3. Clipped term
        clipped_ratio = torch.clamp(pi_ratio, 1 - clip_range, 1 + clip_range)
        clipped = advantages * clipped_ratio

        # 4. Take elementwise minimum and negate (PPO-style objective)
        loss = -torch.minimum(unclipped, clipped)

        # Optional metadata for logging/debugging
        stats = {
        "ratio_mean": pi_ratio.mean(),
        "ratio_std": pi_ratio.std(),
        "ratio_min": pi_ratio.min(),
        "ratio_max": pi_ratio.max(),
    }
    
    ### END YOUR CODE ###
    return loss, stats


def masked_mean(tensor: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
    """
    Compute the mean of tensor values where mask=True for each row, then average across the batch.
    """
    ### YOUR CODE HERE ###
    # Convert mask to float for proper multiplication
    mask = mask.float()
    
    # Sum over tokens for each sequence, considering only response tokens
    masked_sum = (tensor * mask).sum(dim=1)
    
    # Count valid tokens per sequence
    token_count = mask.sum(dim=1).clamp(min=1)
    
    # Mean over valid tokens in each sequence, then average across batch
    mean_per_seq = masked_sum / token_count
    loss = mean_per_seq.mean()
    ### END YOUR CODE ###
    return loss

def masked_mean_drgrpo(tensor: torch.Tensor, mask: torch.Tensor, num_tokens: int) -> torch.Tensor:
    """
    Compute the sum of tensor values where mask=True, divided by num_tokens, then average across the batch.
    This is used for the DR-GRPO loss
    """
    ### YOUR CODE HERE ###
    # Convert mask to float for proper multiplication
    mask = mask.float()
    
    masked_sum = (tensor * mask).sum(dim=1)
    
    # Divide by fixed constant num_tokens (same for all sequences)
    mean_per_seq = masked_sum / float(num_tokens)
    loss = mean_per_seq.mean()
    ### END YOUR CODE ###
    return loss

def get_response_log_probs(model: PreTrainedModel, input_ids: torch.Tensor, labels: torch.Tensor) -> torch.Tensor:
    logits = model(input_ids).logits
    log_probs = F.log_softmax(logits, dim=-1)
    log_probs = torch.gather(log_probs, dim=-1, index=labels.unsqueeze(-1)).squeeze(-1)
    return log_probs


# Training helpers and loop
def duplicate_data(arr: List, group_size: int) -> List:
    return [x for x in arr for _ in range(group_size)]


def rollout_with_vllm(policy: PreTrainedModel, llm: LLM, sampling_params: SamplingParams, prompts_batch: List[str], group_size: int) -> Tuple[List[str], List[str], List[int]]:
    load_policy_into_vllm_instance(policy, llm)
    prompts_dup = duplicate_data(prompts_batch, group_size)
    vllm_rollouts = llm.generate(prompts_dup, sampling_params, use_tqdm=False)
    rollout_input_text, rollout_response_text, rollout_output_tokens = [], [], []
    for rollout in vllm_rollouts:
        for r in rollout.outputs:
            rollout_input_text.append(rollout.prompt)
            rollout_response_text.append(r.text)
            rollout_output_tokens.append(len(llm.llm_engine.tokenizer.encode(r.text)))
    return rollout_input_text, rollout_response_text, rollout_output_tokens


def tokenize_rollouts(rollout_input_text: List[str], rollout_response_text: List[str], tokenizer: AutoTokenizer) -> Dict[str, torch.Tensor]:
    return tokenize_prompt_and_output(rollout_input_text, rollout_response_text, tokenizer)


def grpo_microbatch_step(
    policy: PreTrainedModel, input_ids: torch.Tensor, labels: torch.Tensor, response_mask: torch.Tensor,
    advantages_per_seq: torch.Tensor, gradient_accumulation_steps: int, clip_range: float,
    loss_type: str = "grpo", max_completion_length: int = 512, training_mode: str = "grpo",
    response_filter_mask: torch.Tensor = None,
) -> Tuple[torch.Tensor, Dict[str, torch.Tensor]]:
    """
    Perform a microbatch gradient step.
    
    Args:
        policy: The policy model
        input_ids: Input token IDs
        labels: Target token IDs
        response_mask: Mask indicating which tokens are part of the response
        advantages_per_seq: Advantages for each sequence
        gradient_accumulation_steps: Number of gradient accumulation steps
        clip_range: Clipping range for PPO
        loss_type: Type of loss computation ("grpo" or "dr_grpo")
        max_completion_length: Maximum completion length for dr_grpo
        training_mode: Training mode ("grpo", "nsr", "weighted_reinforce")
        response_filter_mask: For NSR, mask indicating which responses to train on
    
    Returns:
        loss: Scalar loss value
        metadata: Dictionary with training statistics
    """
    # For NSR modes, filter out responses we don't want to train on
    if response_filter_mask is not None and training_mode in ["nsr", "weighted_reinforce"]:
        # Apply filter mask - only compute loss on selected responses
        if not response_filter_mask.any():
            # All responses are correct, no training needed
            return torch.tensor(0.0), {"ratio_mean": torch.tensor(1.0), "ratio_std": torch.tensor(0.0),
                                       "ratio_min": torch.tensor(1.0), "ratio_max": torch.tensor(1.0)}
    
    policy_log_probs = get_response_log_probs(policy, input_ids, labels)
    old_log_probs = policy_log_probs.detach()
    advantages = advantages_per_seq.unsqueeze(-1)
    
    # Compute loss with training mode
    loss_per_token, metadata = compute_loss(advantages, policy_log_probs, old_log_probs, clip_range, 
                                            training_mode=training_mode)
    
    # Aggregate loss
    if loss_type == "grpo":
        loss = masked_mean(loss_per_token, response_mask)
    elif loss_type == "dr_grpo":
        loss = masked_mean_drgrpo(loss_per_token, response_mask, max_completion_length)
    else:
        raise ValueError(f"Unknown loss type: {loss_type}")
    
    loss = loss / gradient_accumulation_steps
    loss.backward()
    return loss.detach(), metadata


def _compute_advantages_for_mode(
    rollout_response: List[str],
    answers_dup: List[Dict],
    selected_reward_fn: Callable,
    group_size: int,
    training_mode: str,
    advantage_eps: float,
    use_std_normalization: bool,
    nsr_lambda: float,
) -> Tuple[torch.Tensor, torch.Tensor, Dict, torch.Tensor]:
    """Compute advantages based on training mode."""
    if training_mode in ["nsr", "weighted_reinforce"]:
        advantages, raw_rewards, response_filter_mask, reward_meta = compute_nsr_advantages(
            rollout_response, answers_dup, selected_reward_fn, group_size, training_mode, nsr_lambda
        )
    else:
        # Standard GRPO
        advantages, raw_rewards, reward_meta = compute_group_normalized_advantages(
            rollout_response, answers_dup, selected_reward_fn, group_size, advantage_eps, use_std_normalization
        )
        response_filter_mask = None
    return advantages, raw_rewards, reward_meta, response_filter_mask


def _apply_nsr_filtering(
    tokenized: Dict[str, torch.Tensor],
    advantages: torch.Tensor,
    response_filter_mask: torch.Tensor,
    training_mode: str,
) -> Tuple[Dict[str, torch.Tensor], torch.Tensor, bool]:
    """Apply response filtering for NSR mode. Returns (tokenized, advantages, should_skip)."""
    if training_mode == "nsr":
        train_indices = torch.where(response_filter_mask)[0]
        if len(train_indices) == 0:
            return tokenized, advantages, True  # Should skip this batch
        
        # Filter tokenized data to only incorrect responses
        for key in tokenized:
            tokenized[key] = tokenized[key][train_indices]
        advantages = advantages[train_indices]
    
    return tokenized, advantages, False


def _log_training_step(
    train_step: int,
    rollout_loss: float,
    grad_norm: float,
    reward_meta: Dict,
    avg_output_tokens: float,
    training_mode: str,
    all_correct_batch_count: int,
    writer: SummaryWriter,
) -> None:
    """Log training metrics."""
    log_msg = (f"Step {train_step} | Loss: {rollout_loss:.4f} | Grad: {grad_norm:.4f} | "
               f"Reward mean: {reward_meta['mean']:.4f} | Reward std: {reward_meta['std']:.4f}")
    
    if training_mode in ["nsr", "weighted_reinforce"]:
        num_correct = reward_meta.get("num_correct", 0)
        num_incorrect = reward_meta.get("num_incorrect", 0)
        total = num_correct + num_incorrect
        correct_ratio = num_correct / total if total > 0 else 0.0
        log_msg += f" | Correct: {num_correct}/{total} ({correct_ratio*100:.1f}%)"
    
    print(log_msg)
    log_train(rollout_loss, grad_norm, reward_meta, avg_output_tokens, writer, train_step)
    
    # NSR-specific TensorBoard metrics
    if writer and training_mode in ["nsr", "weighted_reinforce"]:
        writer.add_scalar("train/num_correct", reward_meta.get("num_correct", 0), global_step=train_step)
        writer.add_scalar("train/num_incorrect", reward_meta.get("num_incorrect", 0), global_step=train_step)
        writer.add_scalar("train/correct_ratio", correct_ratio, global_step=train_step)
        writer.add_scalar("train/all_correct_batches", all_correct_batch_count, global_step=train_step)


def train(
    policy: PreTrainedModel, tokenizer: AutoTokenizer, llm: LLM, sampling_params: SamplingParams, *,
    train_prompts: List[str], train_answers: List[Dict], eval_prompts: List[str], eval_answers: List[Dict],
    optimizer: torch.optim.Optimizer, scheduler, n_grpo_steps: int, rollout_batch_size: int,
    group_size: int, gradient_accumulation_steps: int, clip_range: float, use_std_normalization: bool,
    advantage_eps: float, device: str, eval_every: int = 5, writer: SummaryWriter = None, seed: int,
    loss_type: str = "grpo", max_completion_length: int = 256, training_mode: str = "grpo",
    use_binary_rewards: bool = False, nsr_lambda: float = 0.1,
) -> None:
    """Main training loop supporting GRPO, NSR, and Weighted-REINFORCE modes."""
    n_prompts_per_rollout_batch = rollout_batch_size // group_size
    micro_train_batch_size = rollout_batch_size // gradient_accumulation_steps
    random.seed(seed)
    train_step = 0
    all_correct_batch_count = 0
    
    # Select reward function based on training mode
    selected_reward_fn = get_reward_fn_for_mode(training_mode, use_binary_rewards)

    # Initial evaluation
    metrics = evaluate_model(llm, sampling_params, eval_prompts, eval_answers)
    if writer:
        for k in ["accuracy", "mean_reward", "std_reward", "avg_output_tokens", "count_correct", "count_partial", "count_failed"]:
            writer.add_scalar(f"eval/{k}", metrics[k], global_step=train_step)
        log_eval(metrics, writer, train_step)

    for _ in range(n_grpo_steps):
        # Sample and rollout
        sampled = random.sample(list(zip(train_prompts, train_answers)), n_prompts_per_rollout_batch)
        prompts_batch, answers_batch = [p for p, _ in sampled], [a for _, a in sampled]
        rollout_input, rollout_response, rollout_tokens = rollout_with_vllm(policy, llm, sampling_params, prompts_batch, group_size)
        answers_dup = duplicate_data(answers_batch, group_size)
        avg_output_tokens = sum(rollout_tokens) / len(rollout_tokens) if rollout_tokens else 0.0
        
        # Compute advantages
        advantages, raw_rewards, reward_meta, response_filter_mask = _compute_advantages_for_mode(
            rollout_response, answers_dup, selected_reward_fn, group_size, training_mode,
            advantage_eps, use_std_normalization, nsr_lambda
        )
        
        # NSR: Skip batch if all responses are correct
        if training_mode == "nsr" and reward_meta.get("num_incorrect", 0) == 0:
            all_correct_batch_count += 1
            print(f"Step {train_step + 1} | All responses correct, skipping (total skipped: {all_correct_batch_count})")
            train_step += 1
            continue
        
        # Tokenize and apply NSR filtering if needed
        tokenized = tokenize_rollouts(rollout_input, rollout_response, tokenizer)
        if training_mode in ["nsr", "weighted_reinforce"] and response_filter_mask is not None:
            tokenized, advantages, should_skip = _apply_nsr_filtering(
                tokenized, advantages, response_filter_mask, training_mode
            )
            if should_skip:
                all_correct_batch_count += 1
                train_step += 1
                continue
        
        # Gradient accumulation
        optimizer.zero_grad()
        rollout_loss = 0.0
        actual_batch_size = tokenized["input_ids"].shape[0]
        
        for micro_idx in range(0, actual_batch_size, micro_train_batch_size):
            end_idx = min(micro_idx + micro_train_batch_size, actual_batch_size)
            s = slice(micro_idx, end_idx)
            loss, _ = grpo_microbatch_step(
                policy, tokenized["input_ids"][s].to(device), tokenized["labels"][s].to(device),
                tokenized["response_mask"][s].to(device), advantages[s].to(device),
                gradient_accumulation_steps, clip_range, loss_type=loss_type, 
                max_completion_length=max_completion_length, training_mode=training_mode,
                response_filter_mask=response_filter_mask[s] if response_filter_mask is not None else None
            )
            rollout_loss += float(loss.item())
        
        # Optimizer step
        grad_norm = torch.nn.utils.clip_grad_norm_([p for p in policy.parameters() if p.grad is not None], 1.0)
        optimizer.step()
        scheduler.step()
        rollout_loss /= max(1, (actual_batch_size // micro_train_batch_size))
        train_step += 1
        
        # Logging
        _log_training_step(train_step, rollout_loss, grad_norm, reward_meta, avg_output_tokens,
                          training_mode, all_correct_batch_count, writer)
        
        # Periodic evaluation
        if train_step % eval_every == 0:
            metrics = evaluate_model(llm, sampling_params, eval_prompts, eval_answers)
            log_eval(metrics, writer, train_step)


def init_policy(model_id: str, device: str) -> Tuple[PreTrainedModel, AutoTokenizer]:
    model = AutoModelForCausalLM.from_pretrained(
        model_id, torch_dtype=torch.bfloat16, attn_implementation="flash_attention_2", use_cache=False
    )
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    model.to(device).train()
    return model, tokenizer


def main() -> None:
    # Hyperparameters
    model_id = "Qwen/Qwen3-1.7B"
    device = "cuda"
    seed, gpu_mem_util = 42, 0.4
    n_grpo_steps, rollout_batch_size, group_size, grad_acc_steps = 150, 128, 8, 32
    lr, clip_range, adv_eps = 7e-6, 0.2, 1e-6
    temperature, min_tokens = 1.0, 4
    eval_every = 10

    # CHANGING HYPERPARAMETERS for main assignment
    loss_type = "grpo" # or "dr_grpo"
    max_tokens = 256 # or 512, 1024
    
    # ===== NSR (Negative Sample Reinforcement) Configuration =====
    # Training mode options: "grpo" (default), "nsr", "weighted_reinforce"
    training_mode = "grpo"  # Change to "nsr" or "weighted_reinforce" for NSR training
    
    # NSR-specific parameters
    nsr_lambda = 0.1  # Weight for correct samples in weighted_reinforce mode (default 0.1)
                      # Lower lambda means less emphasis on correct samples
                      # Typical range: 0.01 to 0.5
    
    use_binary_rewards = False  # Set to True to force binary rewards even in GRPO mode
                                # For NSR modes, this is automatically True
                                # Binary: 1.0 for correct, -1.0 for incorrect (no partial credit)
    
    # Automatically set binary rewards for NSR modes
    if training_mode in ["nsr", "weighted_reinforce"]:
        use_binary_rewards = True
    
    # ===== End NSR Configuration =====
    
    # Initialization
    use_std_norm = loss_type == "grpo" and training_mode == "grpo"  # No std normalization for NSR
    policy, tokenizer = init_policy(model_id=model_id, device=device)
    llm = init_vllm(model_id=model_id, device=device, seed=seed, gpu_memory_utilization=gpu_mem_util)
    sampling_params = init_sampling_params(temperature=temperature, min_tokens=min_tokens, max_tokens=max_tokens)
    
    # Dataset
    def build_dataset(split):
        data = []
        for ex in split:
            prompt = TEMPLATE.format(numbers=ex["nums"], target=ex["target"], max_tokens=max_tokens)
            prompt = tokenizer.apply_chat_template(
                [dict(role="system", content="You are a helpful assistant."),
                dict(role="user", content=prompt)],
                add_generation_prompt=True, tokenize=False)
            data.append({"prompt": prompt,"answer": {"target": ex["target"], "numbers": ex["nums"]},})
        return data

    # Load properly split dataset
    train_data = load_dataset("justinphan3110/Countdown-Tasks-3to4", split="train")
    eval_data = load_dataset("justinphan3110/Countdown-Tasks-3to4", split="test")
    
    train_examples = build_dataset(train_data)
    eval_examples = build_dataset(eval_data)
    
    # Optimizer and Scheduler
    optimizer = torch.optim.AdamW(policy.parameters(), lr=lr, weight_decay=1e-2, betas=(0.9, 0.95))
    scheduler = get_constant_schedule_with_warmup(optimizer=optimizer, num_warmup_steps=0)
    
    # Logging
    timestamp = int(datetime.datetime.now(datetime.timezone.utc).timestamp())
    log_dir = os.path.join("./output", "tb", f"hw_a2_{training_mode}_{loss_type}", str(timestamp))
    os.makedirs(log_dir, exist_ok=True)
    writer = SummaryWriter(log_dir=log_dir)
    
    print(f"=== Training Configuration ===")
    print(f"Training Mode: {training_mode}")
    print(f"Loss Type: {loss_type}")
    print(f"Use Binary Rewards: {use_binary_rewards}")
    print(f"NSR Lambda: {nsr_lambda}")
    print(f"Temperature: {temperature}")
    print(f"Max Tokens: {max_tokens}")
    print(f"Learning Rate: {lr}")
    print(f"=" * 30)
    
    # Training
    train(
        policy=policy, tokenizer=tokenizer, llm=llm, sampling_params=sampling_params,
        train_prompts=[ex["prompt"] for ex in train_examples], train_answers=[ex["answer"] for ex in train_examples],
        eval_prompts=[ex["prompt"] for ex in eval_examples], eval_answers=[ex["answer"] for ex in eval_examples],
        optimizer=optimizer, scheduler=scheduler, n_grpo_steps=n_grpo_steps,
        rollout_batch_size=rollout_batch_size, group_size=group_size,
        gradient_accumulation_steps=grad_acc_steps, clip_range=clip_range,
        use_std_normalization=use_std_norm, advantage_eps=adv_eps, device=device,
        eval_every=eval_every, writer=writer, seed=seed, loss_type=loss_type,
        max_completion_length=max_tokens, training_mode=training_mode,
        use_binary_rewards=use_binary_rewards, nsr_lambda=nsr_lambda
    )
    
    # Save model
    out_dir = os.path.join("./output", f"hw_a2_{training_mode}_{loss_type}_{timestamp}")
    os.makedirs(out_dir, exist_ok=True)
    policy.save_pretrained(out_dir)
    tokenizer.save_pretrained(out_dir)
    print(f"Saved model and tokenizer to {out_dir}")
    writer.close()
    
# Test Function
def test_functions():
    """Quick unit tests for the implemented functions"""
    print("\n=== Running Quick Tests ===")
    
    # Test masked_mean
    print("Testing masked_mean...")
    tensor = torch.randn(4, 10)  # [batch_size=4, seq_len=10]
    mask = torch.tensor([
        [False, False, True, True, True, True, False, False, False, False],
        [False, True, True, True, True, False, False, False, False, False],
        [False, False, False, True, True, True, True, True, False, False],
        [False, False, True, True, True, True, True, False, False, False],
    ])
    result = masked_mean(tensor, mask)
    assert result.shape == torch.Size([]), f"Expected scalar, got shape {result.shape}"
    print(f"✅ masked_mean works! Result: {result.item():.4f}")
    
    # Test masked_mean_drgrpo
    print("Testing masked_mean_drgrpo...")
    result = masked_mean_drgrpo(tensor, mask, num_tokens=256)
    assert result.shape == torch.Size([]), f"Expected scalar, got shape {result.shape}"
    print(f"✅ masked_mean_drgrpo works! Result: {result.item():.4f}")
    
    # Test compute_loss
    print("Testing compute_loss...")
    advantages = torch.randn(4)  # [batch_size=4]
    advantages = advantages.unsqueeze(-1)  # ✅ ADD THIS LINE - simulate grpo_microbatch_step
    policy_log_probs = torch.randn(4, 10)  # [batch_size=4, seq_len=10]
    old_log_probs = torch.randn(4, 10)
    clip_range = 0.2
    
    loss_per_token, stats = compute_loss(advantages, policy_log_probs, old_log_probs, clip_range)
    assert loss_per_token.shape == (4, 10), f"Expected shape (4, 10), got {loss_per_token.shape}"
    assert "ratio_mean" in stats, "Missing ratio_mean in stats"
    print(f"✅ compute_loss works! Loss shape: {loss_per_token.shape}")
    
    # Test compute_group_normalized_advantages
    print("Testing compute_group_normalized_advantages...")
    rollout_responses = ["resp1", "resp2", "resp3", "resp4"]
    ground_truths = [
        {"target": 36, "numbers": [79, 17, 60]},
        {"target": 36, "numbers": [79, 17, 60]},
        {"target": 36, "numbers": [79, 17, 60]},
        {"target": 36, "numbers": [79, 17, 60]},
    ]
    
    advantages, raw_rewards, metadata = compute_group_normalized_advantages(
        rollout_responses, ground_truths, reward_fn, group_size=2, 
        advantage_eps=1e-6, normalize_by_std=True
    )
    assert advantages.shape == (4,), f"Expected shape (4,), got {advantages.shape}"
    assert raw_rewards.shape == (4,), f"Expected shape (4,), got {raw_rewards.shape}"
    assert "mean" in metadata and "std" in metadata, "Missing metadata keys"
    print(f"✅ compute_group_normalized_advantages works!")
    
    print("\n=== All Tests Passed! ===\n")


if __name__ == "__main__":
    # Run quick tests first
    test_functions()
    
    # Then run main training
    main()